### ISSUE TITLE
How to test an image？

### ISSUE THREAD

**Issue by Elaine10** [ceciliavision/perceptual-reflection-removal#1]
Which folder should I put test images into?

What argument should I use?

**Comment by ceciliavision** [comment]
Hi Elaine,

I won't be able to access my work machine until September, so I'm not able to upload the test code and model. Once I have access to the machine I'd make them available with detailed instructions.

**Comment by ceciliavision** [comment]
Hi Elaine,

I have updated the repo with pre-trained model link and test code, please take a look!

**Comment by BlueWinters** [comment]
maybe there is something wrong where loading the vgg19:
`Traceback (most recent call last):
  File "F:/hdfaces/flc/prr/main.py", line 232, in <module>
    network=build(input)
  File "F:/hdfaces/flc/prr/main.py", line 113, in build
    vgg19_features=build_vgg19(input[:,:,:,0:3]*255.0)
  File "F:/hdfaces/flc/prr/main.py", line 89, in build_vgg19
    net['conv1_1']=build_net('conv',net['input'],get_weight_bias(vgg_layers,0),name='vgg_conv1_1')
  File "F:/hdfaces/flc/prr/main.py", line 56, in get_weight_bias
    bias=tf.constant(np.reshape(bias,(bias.size)))
AttributeError: 'str' object has no attribute 'size'`

**Comment by BlueWinters** [comment]
there is something wrong when load the vgg19.mat, it happens in `main.py` and line 56, this is the details:
`
Traceback (most recent call last):
  File "F:/hdfaces/flc/prr/main.py", line 232, in <module>
    network=build(input)
  File "F:/hdfaces/flc/prr/main.py", line 113, in build
    vgg19_features=build_vgg19(input[:,:,:,0:3]*255.0)
  File "F:/hdfaces/flc/prr/main.py", line 89, in build_vgg19
    net['conv1_1']=build_net('conv',net['input'],get_weight_bias(vgg_layers,0),name='vgg_conv1_1')
  File "F:/hdfaces/flc/prr/main.py", line 56, in get_weight_bias
    bias=tf.constant(np.reshape(bias,(bias.size)))
AttributeError: 'str' object has no attribute 'size'
`

**Comment by ceciliavision** [comment]
I don't think it's a problem for me and people who have tested. Could you make sure you have the correct .mat file? just in case I uploaded the correct one [here](https://drive.google.com/open?id=1Wnv4Lc92idbrv_SzajEf62P65Qv2iz-G)

**Comment by BlueWinters** [comment]
thank you for your reply. i found my mistake: i use a another vgg19.mat with a small modification.
