### ISSUE TITLE
identity_initializer

### ISSUE THREAD

**Issue by Candyeeee** [ceciliavision/perceptual-reflection-removal#12]
Dear author,
          I found the way for  initializing variables in your network is different from other ways. I do not understand the function of identity_initializer and when I changed the way of initializing it worked bad. Can you tell me why  you use this initializing way in your network?

**Comment by ceciliavision** [comment]
Our target distribution is close to the input distribution (with and without reflection), so we initialize the network with identity weights. Different types of initialization will affect convergence quite much, an improper initialization may lead to local minimum and very slow convergence even with heavy tuning of hyperparameters. There's been a pile of research works that analyze how different initialization affect different types of tasks. In this work we don't discuss or conduct such ablation study.
