### ISSUE TITLE
num_train=len(syn_image1_list)+len(output_real_names1) cause array index out of bound exception as that file do not exist

### ISSUE THREAD

**Issue by ayyappa-s** [ceciliavision/perceptual-reflection-removal#13]
https://github.com/ceciliavision/perceptual-reflection-removal/blob/master/main.py#L312

Hi @ceciliavision,

somehow the script for training keeps failing at line number https://github.com/ceciliavision/perceptual-reflection-removal/blob/master/main.py#L331 due to the fact that num_train is actually more than the actual count of the image which the synthetic data completely posses, you mind updating the code accordingly or kindly explain how the exception can be escaped

**Comment by ceciliavision** [comment]
Have you checked if you have correctly read in the images? What is the size of your list that reads in the images?

**Comment by ayyappa-s** [comment]
there are totally 13700 images in syn reflection and syn transmission each. on the real reflection it is 24 and real transmission it is 24

**Comment by ayyappa-s** [comment]
![image](https://user-images.githubusercontent.com/280200/52300858-f8661a00-29ae-11e9-8063-1d9bd493c2fb.png)

please see this screenshot total image is 13700 and total input images is 24 since the num_train is 13724 it is looking for id 13704 but syn images doesn't contain that many images (only 13700 per reflection as well transmission - taken from your source @ google drive i have deleted few images to match the count of 13700 in both reflection as well transmission)

**Comment by ayyappa-s** [comment]
kindly suggest whether i can use 

`num_train=len(syn_image1_list)`

instead of

`num_train=len(syn_image1_list)+len(output_real_names1)`

**Comment by ayyappa-s** [comment]
I went by my suggestion and it works for me well without issues
