### ISSUE TITLE
a question about preceptual loss

### ISSUE THREAD

**Issue by laulampaul** [ceciliavision/perceptual-reflection-removal#15]
您好，我想问问您代码中的感知损失，为什么p5最后要*10/1.5，这样最后一层的损失就有点大。一般的p5的损失是不是应该比前面的要小呢？谢谢~

**Comment by laulampaul** [comment]
还有个问题想请教一下，我看代码中的初始化是用使卷积核中间值为1，其他为0。但是我用pytorch复现了一下，您的代码60个iter就能几乎达到原图了，我的网络很久才能恢复出细节，是初始化的原因吗，还是由于其他的原因？

**Comment by ceciliavision** [comment]
每一层的scale不同 这些hyperparameters 是在平衡每一层对损失的贡献 可以理解成是一个normalization。

pytorch里面你用的不一样的初始化么？初始化不同对convergence的影响挺大的 是很有可能的造成convergence时间的不同。
