### ISSUE TITLE
TypeError: Expected cv::UMat for argument 'src'

### ISSUE THREAD

**Issue by Timmmmmms** [ceciliavision/perceptual-reflection-removal#16]
Hi @ceciliavision,
When I run your code, 
`output_image_r=cv2.resize(np.float32(cv2.imread(syn_image2_list[id],-1)),(neww,newh),cv2.INTER_CUBIC)/255.0`

`TypeError: Expected cv::UMat for argument 'src'`

How to fix it?

**Comment by ceciliavision** [comment]
Can you check whether the images are read in successfully?
