### ISSUE TITLE
Synthetic data

### ISSUE THREAD

**Issue by zhcm** [ceciliavision/perceptual-reflection-removal#2]
Thank you very much for your outstanding work! I am trying to reproduce your paper, but I have not found the synthetic dataset mentioned in your paper.So I randomly selected some images from voc 2012.Obviously the result is very bad. I wonder if you will public the synthetic dataset?

**Comment by ceciliavision** [comment]
Sure I can later also publicize the synthetic images I used for my training. However, I don't think there should be difference in what the images are used as long as they are natural images. Someone has told me that he/she was able to use their own images to train the model to a pretty good status. So I suspect that something else is deviating if the result is very bad.

**Comment by zhcm** [comment]
@ceciliavision 非常感谢您的回复！很抱歉我的英语比较差劲，不知道您是否介意我用中文。其实结果也不能说是特别差，只是和论文中的结果比起来还相当不够理想。我发现在训练的时候，虽然 total loss（代码中的loss_l1_r + loss_percep*0.2 + loss_grad）在下降，但是生成模型的loss（代码中的g_loss）一个epoch还没训练完就会开始上升，代码中用100 * total_loss + g_loss来更新生成模型的参数，如果这样的话那g_loss对生成模型的影响就比较小了，我没有改动代码中的任何参数，这是一个合理的现象吗？期待您的回复~

**Comment by ceciliavision** [comment]
这也是有可能出现的 但最终应该是可以converge的 把gan从一开始就加进来可能会对training造成一些不稳定和随机性 你可以先等几个epoch看看是否会converge 如果不可以 你可以尝试开始的时候先不用gan 等train到一个相对稳定到时候再加回去

**Comment by zhcm** [comment]
@ceciliavision 懂了，感谢。顺便说一句，摄影技术非常赞

**Comment by rohansinghjain** [comment]
Hi @ceciliavision, is the synthetic training dataset public now? Please let me know.

**Comment by ceciliavision** [comment]
> Hi @ceciliavision, is the synthetic training dataset public now? Please let me know.

Yes! Both real and synthetic dataset are public, you can find them [here](https://drive.google.com/drive/folders/1NYGL3wQ2pRkwfLMcV2zxXDV8JRSoVxwA?usp=sharing). The way to use them is described in this GitHub main page.
