### ISSUE TITLE
How to split the real dataset as you have done in the paper?

### ISSUE THREAD

**Issue by Vandermode** [ceciliavision/perceptual-reflection-removal#3]
Hi, I would like to know how to split the testing set as you have done in the paper, i.e. 90 for training and 20 for testing. Since the pretrained model has already utilized the 90 images from real dataset, it's unfair to compare it with other methods on the whole real dataset.

**Comment by ceciliavision** [comment]
the real dataset contains both training and testing used in the pre-trained model. I used indexing to split them, but don't have the indices at hand. All the test results should be showed in the paper and supplementary material. I will add the supplementary material to this site later. You can find out which images are used for testing.

**Comment by Vandermode** [comment]
Thank you for your attention. Follow your instruction, I find totally 13 images used for testing. However, it does not match the number (i.e. 20) described in the paper. Also the image in Figure 4 (of the original paper) is missing in the provided real dataset. Though it's acceptable to evaluate the performance in these images (12 in total), I was wondering if it's possible to reproduce the result listed in table 1 of the original paper. 
Here are the indices I have found:
```
19.jpg
23.jpg
25.jpg
46.jpg
4.jpg
22.jpg
3.jpg
11.jpg
15.jpg
9.jpg
89.jpg
93.jpg
```
I also notice almost every images displayed in the paper have been cropped from the original image, which makes the reproduction of table 1 more difficult, if not impossible.

**Comment by ceciliavision** [comment]
uploaded the missing data pair
test indices based on _the order in Google Drive folder_:
3
4
9
12
15
22
23
25
29
39
46
47
58
86
87
89
93
103
107
110

**Comment by Vandermode** [comment]
Thank you for your reply, which helps me a lot, but I still meet the problem when evaluating the pretrained model in testing set.

Specifically, I cannot evaluate some images due to the memory issue as follow:
```
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,945,811,1475]
```
The hyper-column features in your model require too much memory to fit in a single NVIDIA GTX 1080 GPU with 11GB memory. I just was wondering whether the results reported in the paper are obtained in a cropped version of testing set or not.

If the full resolution images was used as input, maybe I should resort to a GPU server to fulfill the memory requirement.

**Comment by ceciliavision** [comment]
right, you have to crop the images (depending on the GPU memory, the cropped images should preserve the global context) to fit the memory for hypercolumn features. I need to look into a bit to get the exact cropped images I used, but it shouldn't differ much if you just crop enough to fit the memory and then test.

**Comment by Vandermode** [comment]
well, I simply center crop 512 x 512 regions from all testing images, but get a slightly worse result compared with table 1. I will manually select 512 x 512 region from each image to preserve the reflection regions.

**Comment by Vandermode** [comment]
wait... there is still a problem in the released real dataset.
When I inspect the testing images carefully, I find the transmission and blended images of same image pair have inconsistent size, e.g. 3.jpg
Here are the total list of images (110 from real dataset) which have inconsistent size issue:
```
10 (910, 1310, 3) (1945, 2940, 3)
29 (934, 979, 3) (1494, 1894, 3)
3 (968, 1118, 3) (1935, 2942, 3)
86 (741, 1147, 3) (2304, 3456, 3)
```

**Comment by ceciliavision** [comment]
hmm that's weird, it was the correct size in my local folder, of which I used to directly upload to Gdrive. I fixed those images. Thanks for figuring out these mess.
