### ISSUE TITLE
What's the 5000 training images of the systhetic dataset.

### ISSUE THREAD

**Issue by lihaoliu-cambridge** [ceciliavision/perceptual-reflection-removal#7]
Hello, thanks for sharing your code.

You mentioned that you use 5k synthetic images from your dataset for training and test on synthetic
data provided by CEILNet (8.5k).

The link you share contains 13.5k images. 

I assume it contains all the images from your dataset (5k) and CEILNet dataset (8.5k).

Could you tell me which ones are from your dataset and which ones are from CEILNet dataset?

Thanks.

**Comment by ceciliavision** [comment]
Hello,

The repo contains all images I scrapped from Flickr but I didn't use them all. There is no synthetic data from CEILNet in that repo. For their synthetic test images, which we tested on, you can find in their github repo.[https://github.com/fqnchina/CEILNet/tree/master/testdata_reflection_synthetic](url)

**Comment by lihaoliu-cambridge** [comment]
Dear Cecilia:

Thanks for the reply.

If possible, could you please tell me the index of the 5000 images you used.

I want to re-implement your experiment using pytorch.

So if you can tell me the index, it would be better for comparison.

--
Best,
Lihao.

Cecilia Zhang <notifications@github.com> 于2018年10月24日周三 下午12:01写道：

**Comment by ceciliavision** [comment]
Actually, now I remember, this should be the image patches cropped from the 5K images I scrapped, so I used all these patches for training. Sorry for the previous misleading answer.

**Comment by lihaoliu-cambridge** [comment]
Okay, I understand now. Thanks for your prompt reply.

Cecilia Zhang <notifications@github.com> 于2018年10月24日周三 下午1:15写道：

**Comment by leftthomas** [comment]
@ceciliavision There are two dirs named `testdata_reflection_synthetic` and `testdata_reflection_synthetic_table2`, which one you used to test with?
