### ISSUE TITLE
The resolution of your real testing images?

### ISSUE THREAD

**Issue by csqiangwen** [ceciliavision/perceptual-reflection-removal#9]
Could you tell me the resolution of the images when you tested your model on your real data? Because the original resolution of your real data is too big for our Titan Xp GPU.

**Comment by ceciliavision** [comment]
I tested on resized images and you can do so to fit into GPU memory. Alternatively, you can test on CPU, with the tradeoff being the speed, but it should be able to run the test in full res.

**Comment by csqiangwen** [comment]
Thanks
